
# List all executables to build
all: run_ex1 run_ex2 run_ex3 run_ex4 run_ex5 run_ex6 run_ex7 run_ex8

run_ex1:
	g++ -O3 -Wall -Werror -std=c++14 -I../../eigen/ ex1.cpp -o run_ex1

run_ex2:
	g++ -O3 -Wall -Werror -std=c++14 -I../../eigen/ ex2.cpp -o run_ex2

run_ex3:
	g++ -O3 -Wall -Werror -std=c++14 -I../../eigen/ ex3.cpp -o run_ex3

run_ex4:
	g++ -O3 -Wall -Werror -std=c++14 -I../../eigen/ ex4.cpp -o run_ex4

run_ex5:
	g++ -O3 -Wall -Werror -std=c++14 -I../../eigen/ ex5.cpp -o run_ex5

run_ex6:
	g++ -O3 -Wall -Werror -std=c++14 -I../../eigen/ ex6.cpp -o run_ex6

run_ex7:
	g++ -O3 -Wall -Werror -std=c++14 -I../../eigen/ ex7.cpp -o run_ex7

run_ex8:
	g++ -O3 -Wall -Werror -std=c++14 -I../../eigen/ ex8.cpp -o run_ex8

# Remove all run_ex* files
clean:
	rm run_ex*
